# -*- coding: utf-8 -*-
"""streamlit_covid19_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fQvHbPzvI1kYlP-Puzl0Gh2wvP0KRI8a
"""

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

df = pd.read_csv("batch2assignment.csv")
df.head()

df['Date'] = pd.to_datetime(df['Date'])
df.fillna(0,inplace=True)

total_confirmed = df['Confirmed'].sum()
total_deaths = df['Deaths'].sum()
total_recovered = df['Recovered'].sum()
print("Total confirmed:", total_confirmed)
print("Total Deaths:", total_deaths)
print("Total Recovered", total_recovered)

fig1 = px.bar(df, x='Region',y='Confirmed',title='Confirmed Cases by Region')
fig1.show()

trend = df.groupby('Date')[['Confirmed','Deaths','Recovered']].sum().reset_index()
fig2 = px.line(trend, x='Date',y=['Confirmed','Deaths','Recovered'],title='COVID-19 Trend Over Time')
fig2.show()

fig3 = px.pie(values=[total_confirmed, total_deaths, total_recovered], names=['Confirmed','Deaths','Recovered'], title='Overall Distribution')
fig3.show()

region = input("Enter Region: ")
filtered = df[df['Region'] == region]
px.line(filtered, x='Date', y='Confirmed',
        title=f"{region} Trend").show()